---
title: 'Explanatory Coexistence: R Code for Wrangling PsychoPy China Data '
author: "Rui Wang"
date: "`r Sys.Date()`"
output: html_document

Due to ethics and data privacy concerns, the raw data corresponding to this file has not been uploaded. However, I have uploaded the code to demonstrate the data wrangling process.
---

```{r Import Data, include=FALSE}
# Load libraries
library(tidyverse) # Load Tidyverse library - used for data wrangling
library(dplyr) # For data wrangling
library(readxl) # Load readxl library - used for data wrangling needed here to combine the excel files
files <- read_excel("Qualtrics_CNadults_ALL_files.xlsx")
```

```{r Clean Data, include=FALSE}
# Select the specific info that could be used in the manuscript, give the variables names that are more clear
CleanFiles <- dplyr::rename (.data = files, Age = Age) %>% 
  dplyr::rename (Gender = Q5) %>% 
  dplyr::rename (FirstLanguage = Q38)%>%
  dplyr::rename (CurrentStudent = Q6) %>%
  dplyr::rename (CurrentEd = Q7) %>% 
  dplyr::rename (CurrentEd_Info = Q7_4_TEXT) %>% 
  dplyr::rename (HighestEducation = Q8) %>% 
  dplyr::rename (HighestEd_Info = Q8_15_TEXT) %>%
  dplyr::rename (CurrentSubject = Q9) %>%
  dplyr::rename (OtherUndergrad = Q11) %>% 
  dplyr::rename (OtherUndergradSubject = Q12) %>%
  dplyr::rename (MastersCountry = Q18) %>% 
  dplyr::rename (MastersSubject = Q13) %>%
  dplyr::rename (OtherMasters = Q25) %>%
  dplyr::rename (OtherMastersCountry = Q27) %>%
  dplyr::rename (DoctoralCountry = Q24) %>%
  dplyr::rename (PreUniCountry_info_primary = Q15_4_TEXT) %>%
  dplyr::rename (PreUniCountry_info_junior = Q15_5_TEXT) %>%
  dplyr::rename (PreUniCountry_info_secondaryCollege = Q15_11_TEXT) %>%
  dplyr::rename (PreUniCountry_info_high = Q15_6_TEXT) %>%
  dplyr::rename (PreUniCountry_info_highprof = Q15_7_TEXT) %>%
  dplyr::rename (PreUniCountry_info_undergrad = Q15_8_TEXT) %>%
  dplyr::rename (PreUniCountry_info_master = Q15_9_TEXT) %>%
  dplyr::rename (PreUniCountry_info_phd = Q15_10_TEXT) %>%
  dplyr::rename (HighestBiology = Q14_1) %>% 
  dplyr::rename (HighestChemistry = Q14_2) %>% 
  dplyr::rename (HighestPhysics = Q14_3) %>% 
  dplyr::rename (HighestEngineering = Q14_4) %>% 
  dplyr::rename (HighestMathematics = Q14_5) %>% 
  dplyr::rename (HighestPsychology = Q14_6) %>% 
  dplyr::rename (HighestOtherScience = Q14_7) %>% 
  dplyr::rename (HighestOtherScience_Info = Q14_7_TEXT) %>% 
  dplyr::rename (TaughtScience = Q16) %>%
  dplyr::rename (TaughtScienceSubject = Q17) %>%
  dplyr::rename (TaughtScienceStage = Q34) %>%
  dplyr::rename (TaughtScienceStage_info = Q34_10_TEXT)
  

Qualtrics_data <- dplyr::select (.data = CleanFiles, ParticipantID, date, Experiment, Age, Gender, FirstLanguage, CurrentStudent, CurrentEd, CurrentEd_Info, HighestEducation, HighestEd_Info, CurrentSubject, OtherUndergrad, OtherUndergradSubject, MastersCountry, MastersSubject, OtherMasters, OtherMastersCountry, DoctoralCountry, PreUniCountry_info_primary, PreUniCountry_info_junior, PreUniCountry_info_secondaryCollege, PreUniCountry_info_high, PreUniCountry_info_highprof, PreUniCountry_info_undergrad, PreUniCountry_info_master, PreUniCountry_info_phd, HighestBiology, HighestChemistry, HighestPhysics, HighestEngineering, HighestMathematics, HighestPsychology, HighestOtherScience, HighestOtherScience_Info, TaughtScience, TaughtScienceSubject, TaughtScienceStage, TaughtScienceStage_info)


```

```{r revise places and language}
# In this section, there is further tidying - basically it included defining some of the existing variables as factors (to get frequency counts later), adding in Version information, coding the country/language backgrounds of the participants, and creating education scores.

DEMOprocess <- mutate (.data = Qualtrics_data) %>%
  mutate (Gender= dplyr::case_when (Gender == "男" ~ "Male", 
                                    Gender == "女" ~ "Female", 
                                    Gender == "28" ~ "NA", 
                                    Gender == "female" ~ "Female", 
                                    Gender == "男性" ~ "Male", 
                                    Gender == "女性" ~ "Female",
                                             )) %>% 
  mutate (CN_FirstLanguage= dplyr::case_when (FirstLanguage == "汉语" ~ "Chinese", 
                                             FirstLanguage == "中文" ~ "Chinese", 
                                             FirstLanguage == "普通话"~ "Chinese", 
                                             FirstLanguage == "汉语普通话" ~ "Chinese", 
                                             FirstLanguage == "chinese" ~ "Chinese", 
                                             FirstLanguage == "汉语（普通话）" ~ "Chinese", 
                                             FirstLanguage == "拆腻子" ~ "Chinese", 
                                             FirstLanguage == "粤语" ~ "Chinese", 
                                             FirstLanguage == "Mandrain" ~ "Chinese", 
                                             FirstLanguage == "汉" ~ "Chinese", 
                                             FirstLanguage == "Chinese" ~ "Chinese", 
                                             FirstLanguage == "Maderin" ~ "Chinese",
                                             FirstLanguage == "汉语-普通话" ~ "Chinese",
                                             FirstLanguage == "中文普通话" ~ "Chinese",
                                             FirstLanguage == "汉语普通话/西安方言" ~ "Chinese",
                                             FirstLanguage == "Mandarin" ~ "Chinese",
                                             FirstLanguage == "mandarin（simplified）" ~ "Chinese",
                                             FirstLanguage == "宜昌话" ~ "Chinese",
                                             )) %>% 
  # The questionnaire in Chinese does not include questions about nationality, but based on first language and other location information from school days, we mark all participants in this study as Chinese.
    mutate(Site = "CN")%>% 
    mutate (Country_info_junior = dplyr::case_when (PreUniCountry_info_primary == "四川省" ~ "Chinese", 
                                      PreUniCountry_info_primary == "河南" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国，广东" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国" ~ "Chinese",
                                      PreUniCountry_info_primary == "山东" ~ "Chinese",
                                      PreUniCountry_info_primary == "湖南" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国大陆" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国大陆云南省" ~ "Chinese",
                                      PreUniCountry_info_primary == "河南省" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国河南" ~ "Chinese",
                                      PreUniCountry_info_primary == "湖北" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国湖北" ~ "Chinese",
                                      PreUniCountry_info_primary == "广西壮族自治区" ~ "Chinese",
                                      PreUniCountry_info_primary == "湖南省" ~ "Chinese",
                                      PreUniCountry_info_primary == "云南" ~ "Chinese",
                                      PreUniCountry_info_primary == "广州" ~ "Chinese",
                                      PreUniCountry_info_primary == "北京市" ~ "Chinese",
                                      PreUniCountry_info_primary == "贵州" ~ "Chinese",
                                      PreUniCountry_info_primary == "白鹤小学" ~ "Chinese",
                                      PreUniCountry_info_primary == "江西" ~ "Chinese",
                                      PreUniCountry_info_primary == "辽宁" ~ "Chinese",
                                      PreUniCountry_info_primary == "山东省" ~ "Chinese",
                                      PreUniCountry_info_primary == "江西" ~ "Chinese",
                                      PreUniCountry_info_primary == "辽宁" ~ "Chinese",
                                      PreUniCountry_info_primary == "江苏" ~ "Chinese",
                                      PreUniCountry_info_primary == "安徽" ~ "Chinese",
                                      PreUniCountry_info_primary == "山西" ~ "Chinese",
                                      PreUniCountry_info_primary == "广东" ~ "Chinese",
                                      PreUniCountry_info_primary == "广西" ~ "Chinese",
                                      PreUniCountry_info_primary == "福建省" ~ "Chinese",
                                      PreUniCountry_info_primary == "浙江" ~ "Chinese",
                                      PreUniCountry_info_primary == "广西壮族自治区" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国浙江" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国天津" ~ "Chinese",
                                      PreUniCountry_info_primary == "陕西省" ~ "Chinese",
                                      PreUniCountry_info_primary == "新太镇小学" ~ "Chinese",
                                      PreUniCountry_info_primary == "云南省昆明第一小学" ~ "Chinese",
                                      PreUniCountry_info_primary == "吉林省长春市绿园小学" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国四川" ~ "Chinese",
                                      PreUniCountry_info_primary == "内蒙古自治区" ~ "Chinese",
                                      PreUniCountry_info_primary == "China" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国四川省" ~ "Chinese",
                                      PreUniCountry_info_primary == "Shanghai" ~ "Chinese",
                                      PreUniCountry_info_primary == "吉林" ~ "Chinese",
                                      PreUniCountry_info_primary == "天津" ~ "Chinese",
                                      PreUniCountry_info_primary == "上海市" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国江苏" ~ "Chinese",
                                      PreUniCountry_info_primary == "河北" ~ "Chinese",
                                      PreUniCountry_info_primary == "Tianjin" ~ "Chinese",
                                      PreUniCountry_info_primary == "Guangdong" ~ "Chinese",
                                      PreUniCountry_info_primary == "山东省东营市广饶县第一实验小学" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国四川成都" ~ "Chinese",
                                      PreUniCountry_info_primary == "山东省" ~ "Chinese",
                                      PreUniCountry_info_primary == "中华人民共和国" ~ "Chinese",
                                      PreUniCountry_info_primary == "湖北武汉" ~ "Chinese",
                                      PreUniCountry_info_primary == "陕西" ~ "Chinese", 
                                      PreUniCountry_info_primary == "中国山西" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国 江苏" ~ "Chinese",
                                      PreUniCountry_info_primary == "中国 湖北" ~ "Chinese",
                                      PreUniCountry_info_primary == "Beijing" ~ "Chinese",
                                      )) %>% 
   mutate (Country_info_junior = dplyr::case_when (PreUniCountry_info_junior == "四川省" ~ "Chinese", 
                                      PreUniCountry_info_junior == "河南" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国，广东" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国大陆云南省" ~ "Chinese",
                                      PreUniCountry_info_junior == "广西壮族自治区" ~ "Chinese",
                                      PreUniCountry_info_junior == "山东" ~ "Chinese",
                                      PreUniCountry_info_junior == "湖南" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国大陆" ~ "Chinese",
                                      PreUniCountry_info_junior == "河南省" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国河南" ~ "Chinese",
                                      PreUniCountry_info_junior == "湖北" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国湖北" ~ "Chinese",
                                      PreUniCountry_info_junior == "广西壮族自治区" ~ "Chinese",
                                      PreUniCountry_info_junior == "湖南省" ~ "Chinese",
                                      PreUniCountry_info_junior == "北京市" ~ "Chinese",
                                      PreUniCountry_info_junior == "贵州" ~ "Chinese",
                                      PreUniCountry_info_junior == "北师大株洲附中" ~ "Chinese",
                                      PreUniCountry_info_junior == "江西" ~ "Chinese",
                                      PreUniCountry_info_junior == "辽宁" ~ "Chinese",
                                      PreUniCountry_info_junior == "山东" ~ "Chinese",
                                      PreUniCountry_info_junior == "山西" ~ "Chinese",
                                      PreUniCountry_info_junior == "江苏" ~ "Chinese",
                                      PreUniCountry_info_junior == "安徽" ~ "Chinese",
                                      PreUniCountry_info_junior == "广东" ~ "Chinese",
                                      PreUniCountry_info_junior == "广西" ~ "Chinese",
                                      PreUniCountry_info_junior == "河南" ~ "Chinese",
                                      PreUniCountry_info_junior == "福建省" ~ "Chinese",
                                      PreUniCountry_info_junior == "浙江" ~ "Chinese",
                                      PreUniCountry_info_junior == "山东省" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国浙江，上海浦东" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国天津" ~ "Chinese",
                                      PreUniCountry_info_junior == "陕西省" ~ "Chinese",
                                      PreUniCountry_info_junior == "北师大株洲附中" ~ "Chinese",
                                      PreUniCountry_info_junior == "邱县实验中学" ~ "Chinese",
                                      PreUniCountry_info_junior == "云南省昆明第二中学" ~ "Chinese",
                                      PreUniCountry_info_junior == "湖北省宜昌市第五中学" ~ "Chinese",
                                      PreUniCountry_info_junior == "美国" ~ "English",
                                      PreUniCountry_info_junior == "中国四川" ~ "Chinese", 
                                      PreUniCountry_info_junior == "内蒙古自治区" ~ "Chinese",
                                      PreUniCountry_info_junior == "Shanghai" ~ "Chinese",
                                      PreUniCountry_info_junior == "吉林" ~ "Chinese",
                                      PreUniCountry_info_junior == "北京" ~ "Chinese",
                                      PreUniCountry_info_junior == "上海市" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国上海" ~ "Chinese",
                                      PreUniCountry_info_junior == "天津" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国江苏" ~ "Chinese", 
                                      PreUniCountry_info_junior == "Beijing" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国，新加坡" ~ "Chinese, English",
                                      PreUniCountry_info_junior == "河北" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国北京" ~ "Chinese",
                                      PreUniCountry_info_junior == "Tianjin" ~ "Chinese",
                                      PreUniCountry_info_junior == "Guangdong" ~ "Chinese",
                                      PreUniCountry_info_junior == "山东省东营市广饶县第一实验中学" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国四川成都" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国、新加坡" ~ "Chinese, English",
                                      PreUniCountry_info_junior == "中华人民共和国" ~ "Chinese",
                                      PreUniCountry_info_junior == "湖北武汉" ~ "Chinese",
                                      PreUniCountry_info_junior == "陕西" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国山西" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国 江苏" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国江苏" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国 湖北" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国浙江" ~ "Chinese",
                                      PreUniCountry_info_junior == "中国，英国" ~ "Chinese, English")) %>%
  mutate (Country_info_secondaryCollege = dplyr::case_when (
                                      PreUniCountry_info_secondaryCollege == "湖南" ~ "Chinese", 
                                      PreUniCountry_info_secondaryCollege == "中国" ~ "Chinese",
                                      PreUniCountry_info_secondaryCollege == "河南" ~ "Chinese",
                                      PreUniCountry_info_secondaryCollege == "山东" ~ "Chinese"))%>%
  mutate (Country_info_high = dplyr::case_when (
                                      PreUniCountry_info_high == "四川省" ~ "Chinese", 
                                      PreUniCountry_info_high == "河南" ~ "Chinese",
                                      PreUniCountry_info_high == "河南省" ~ "Chinese",
                                      PreUniCountry_info_high == "中国，广东" ~ "Chinese",
                                      PreUniCountry_info_high == "中国" ~ "Chinese",
                                      PreUniCountry_info_high == "山东" ~ "Chinese",
                                      PreUniCountry_info_high == "湖南" ~ "Chinese",
                                      PreUniCountry_info_high == "中国大陆" ~ "Chinese",
                                      PreUniCountry_info_high == "中国河南" ~ "Chinese",
                                      PreUniCountry_info_high == "湖北" ~ "Chinese",
                                      PreUniCountry_info_high == "中国湖北" ~ "Chinese",
                                      PreUniCountry_info_high == "广西壮族自治区" ~"Chinese",
                                      PreUniCountry_info_high == "宁夏回族自治区" ~"Chinese",
                                      PreUniCountry_info_high == "宁夏回族自治区银川市" ~"Chinese", 
                                      PreUniCountry_info_high == "湖南省" ~ "Chinese",
                                      PreUniCountry_info_high == "中国大陆云南省" ~ "Chinese",
                                      PreUniCountry_info_high == "北师大株洲附中" ~ "Chinese",
                                      PreUniCountry_info_high == "江西" ~ "Chinese",
                                      PreUniCountry_info_high == "辽宁" ~ "Chinese",
                                      PreUniCountry_info_high == "江苏" ~ "Chinese",
                                      PreUniCountry_info_high == "安徽" ~ "Chinese",
                                      PreUniCountry_info_high == "山西" ~ "Chinese",
                                      PreUniCountry_info_high == "广东" ~ "Chinese",
                                      PreUniCountry_info_high == "广西" ~ "Chinese",
                                      PreUniCountry_info_high == "福建省" ~ "Chinese",
                                      PreUniCountry_info_high == "浙江" ~ "Chinese",
                                      PreUniCountry_info_high == "山东省" ~ "Chinese",
                                      PreUniCountry_info_high == "中国天津" ~ "Chinese",
                                      PreUniCountry_info_high == "陕西省" ~ "Chinese",
                                      PreUniCountry_info_high == "上海浦东，上海虹口，上海杨浦" ~"Chinese",
                                      PreUniCountry_info_high == "美国" ~"English",
                                      PreUniCountry_info_high == "云南省昆明第二中学高中部" ~ "Chinese", 
                                      PreUniCountry_info_high == "湖北省宜昌市第一中学" ~ "Chinese",
                                      PreUniCountry_info_high == "中国四川" ~ "Chinese",
                                      PreUniCountry_info_high == "内蒙古自治区" ~ "Chinese",
                                      PreUniCountry_info_high == "上海" ~ "Chinese",
                                      PreUniCountry_info_high == "China" ~ "Chinese",
                                      PreUniCountry_info_high == "中国四川省" ~ "Chinese",
                                      PreUniCountry_info_high == "Shanghai" ~ "Chinese",
                                      PreUniCountry_info_high == "吉林" ~ "Chinese",
                                      PreUniCountry_info_high == "天津" ~ "Chinese",
                                      PreUniCountry_info_high == "中国上海" ~ "Chinese",
                                      PreUniCountry_info_high == "爱尔兰" ~ "English",
                                      PreUniCountry_info_high == "加拿大" ~ "English",
                                      PreUniCountry_info_high == "中国江苏" ~ "Chinese",
                                      PreUniCountry_info_high == "Beijing" ~ "Chinese",
                                      PreUniCountry_info_high == "新加坡" ~ "English",
                                      PreUniCountry_info_high == "河北" ~ "Chinese",
                                      PreUniCountry_info_high == "Cambridge" ~ "English",
                                      PreUniCountry_info_high == "Guangdong" ~ "Chinese",
                                      PreUniCountry_info_high == "山东省广饶一中" ~ "Chinese", 
                                      PreUniCountry_info_high == "中国四川成都" ~ "Chinese", 
                                      PreUniCountry_info_high == "中国境内加拿大国际学校" ~ "English",
                                      PreUniCountry_info_high == "中华人民共和国" ~ "Chinese",
                                      PreUniCountry_info_high == "湖北武汉" ~ "Chinese",
                                      PreUniCountry_info_high == "陕西" ~ "Chinese",
                                      PreUniCountry_info_high == "广东省" ~ "Chinese",
                                      PreUniCountry_info_high == "中国北京" ~ "Chinese",
                                      PreUniCountry_info_high == "中国 江苏" ~ "Chinese",
                                      PreUniCountry_info_high == "中国/英国" ~ "Chinese/English",
                                      PreUniCountry_info_high == "英国伦敦" ~ "English",
                                      PreUniCountry_info_high == "中国 湖北" ~ "Chinese",
                                      PreUniCountry_info_high == "Beijing" ~ "Chinese",
                                      PreUniCountry_info_high == "中国浙江" ~ "Chinese",
                                      PreUniCountry_info_high == "新西兰" ~ "English",
                                      PreUniCountry_info_high == "英国" ~ "English")) %>%
  mutate (Country_info_highprof = dplyr::case_when (PreUniCountry_info_highprof == "湖南" ~ "Chinese", 
                                      PreUniCountry_info_highprof == "中国湖北" ~ "Chinese",
                                      PreUniCountry_info_highprof == "湖南" ~ "Chinese",
                                      PreUniCountry_info_highprof == "中国" ~ "Chinese",
                                      PreUniCountry_info_highprof == "日本" ~ "Japanese"))%>%
  mutate (Country_info_undergrad = dplyr::case_when ( 
                                      PreUniCountry_info_undergrad == "湖南省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "湖南" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国湖南" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国大陆湖南省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "湖北" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国湖南省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "浙江" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国大陆云南省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "河南省" ~"Chinese",
                                      PreUniCountry_info_undergrad == "河南" ~"Chinese",
                                      PreUniCountry_info_undergrad == "中国四川" ~"Chinese", 
                                      PreUniCountry_info_undergrad == "陕西省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "四川省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "湖北省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "湖北武汉" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "湖北省武汉市" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "上海市" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "英国" ~ "English",
                                      PreUniCountry_info_undergrad == "四川省四川大学" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "北京" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "辽宁省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国 湖北" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "江苏" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "山东" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "安徽" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国 北京" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "河北省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "陕西" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "江西" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "福建" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "辽宁" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "牛津大学" ~ "English",
                                      PreUniCountry_info_undergrad == "北京市" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "福建省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "四川省四川大学" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "西南交通大学" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国/英国" ~ "Chinese/English",
                                      PreUniCountry_info_undergrad == "中国陕西" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "甘肃省" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "UCL，伦敦大学学院" ~ "English", 
                                      PreUniCountry_info_undergrad == "中国，北京" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国上海" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "中国天津" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "澳大利亚" ~"English",
                                      PreUniCountry_info_undergrad == "美国" ~"English",
                                      PreUniCountry_info_undergrad == "北京理工大学" ~"Chinese",
                                      PreUniCountry_info_undergrad == "英国" ~"English",
                                      PreUniCountry_info_undergrad == "中国福建" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "福建+澳门" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "浙江和英国" ~ "Chinese+English",
                                      PreUniCountry_info_undergrad == "云南大学" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "福建省厦门市厦门大学" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "新加坡/法国" ~ "English/French",
                                      PreUniCountry_info_undergrad == "内蒙古自治区" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "日本" ~ "Japanese",
                                      PreUniCountry_info_undergrad == "Hong Kong SAR, China" ~ "English",
                                      PreUniCountry_info_undergrad == "加拿大" ~ "English",
                                      PreUniCountry_info_undergrad == "中国四川省，美国" ~ "Chinese+English",
                                      PreUniCountry_info_undergrad == "Japan / Singapore" ~ "English+Japanese",
                                      PreUniCountry_info_undergrad == "中国山西及俄罗斯" ~ "Chinese+Russian",
                                      PreUniCountry_info_undergrad == "澳大利亚" ~ "English",
                                      PreUniCountry_info_undergrad == "江苏省；英国" ~ "Chinese+English", 
                                      PreUniCountry_info_undergrad == "大连" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "天津（半年）/日本（4年）" ~ "Chinese+Japanese",
                                      PreUniCountry_info_undergrad == "爱尔兰" ~ "English",
                                      PreUniCountry_info_undergrad == "杭州" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "Shannxi" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "香港" ~ "English",
                                      PreUniCountry_info_undergrad == "中国，英国" ~ "Chinese+English",
                                      PreUniCountry_info_undergrad == "London" ~ "English",
                                      PreUniCountry_info_undergrad == "UK" ~ "English",
                                      PreUniCountry_info_undergrad == "University College London" ~ "English",
                                      PreUniCountry_info_undergrad == "中国，美国" ~ "Chinese+English",
                                      PreUniCountry_info_undergrad == "日本东京" ~ "Japanese",
                                      PreUniCountry_info_undergrad == "英国剑桥" ~ "English",
                                      PreUniCountry_info_undergrad == "中国上海和英国2+2" ~ "Chinese+English",
                                      PreUniCountry_info_undergrad == "中国和英国" ~ "Chinese+English",
                                      PreUniCountry_info_undergrad == "英国 剑桥" ~ "English",
                                      PreUniCountry_info_undergrad == "Shaanxi" ~ "Chinese",
                                      PreUniCountry_info_undergrad == "Canada" ~ "English",)) %>%
  mutate (Country_info_master = dplyr::case_when (PreUniCountry_info_master == "中国" ~ "Chinese",
                                      PreUniCountry_info_master == "德国" ~ "Germany",
                                      PreUniCountry_info_master == "英国" ~ "English",
                                      PreUniCountry_info_master == "英国伦敦大学学院" ~ "English",
                                      PreUniCountry_info_master == "北京市" ~ "Chinese",
                                      PreUniCountry_info_master == "湖北" ~ "Chinese",
                                      PreUniCountry_info_master == "上海" ~ "Chinese",
                                      PreUniCountry_info_master == "福建省" ~ "Chinese",
                                      PreUniCountry_info_master == "北京" ~ "Chinese",
                                      PreUniCountry_info_master == "剑桥大学" ~ "English",
                                      PreUniCountry_info_master == "广东省" ~"Chinese",
                                      PreUniCountry_info_master == "美国" ~"English",
                                      PreUniCountry_info_master == "香港" ~"English", 
                                      PreUniCountry_info_master == "浙江" ~ "Chinese",
                                      PreUniCountry_info_master == "湖南" ~ "Chinese",
                                      PreUniCountry_info_master == "中国/法国" ~ "Chinese/French",
                                      PreUniCountry_info_master == "爱尔兰" ~"English",
                                      PreUniCountry_info_master == "Hong Kong SAR, China" ~"English",
                                      PreUniCountry_info_master == "加拿大" ~"English",
                                      PreUniCountry_info_master == "Hong Kong" ~"English",
                                      PreUniCountry_info_master == "中国香港" ~"English",
                                      PreUniCountry_info_master == "天津" ~ "Chinese",
                                      PreUniCountry_info_master == "日本" ~ "Japanese",
                                      PreUniCountry_info_master == "瑞士" ~ "English",
                                      PreUniCountry_info_master == "中国，英国" ~ "Chinese+English",
                                      PreUniCountry_info_master == "中国/英国" ~ "Chinese+English",
                                      PreUniCountry_info_master == "中国、法国" ~ "Chinese+French",
                                      PreUniCountry_info_master == "UK" ~ "English",
                                      PreUniCountry_info_master == "University College London" ~ "English",
                                      PreUniCountry_info_master == "日本东京" ~ "Japanese",
                                      PreUniCountry_info_master == "英国剑桥" ~ "English",
                                      PreUniCountry_info_master == "Canada" ~ "English",
                                      PreUniCountry_info_master == "中国、英国" ~ "Chinese+English")) %>%
  mutate (PreUniCountry_info_phd_Language = dplyr::case_when (PreUniCountry_info_phd == "英国" ~ "English",
                                      PreUniCountry_info_phd == "英国伦敦国王学院" ~ "English",
                                      PreUniCountry_info_phd == "美国" ~"English",
                                      PreUniCountry_info_phd == "The United Kingdom" ~ "English",
                                      PreUniCountry_info_phd == "爱尔兰" ~ "English",
                                      PreUniCountry_info_phd == "中国香港" ~ "English",
                                      PreUniCountry_info_phd == "英国" ~ "English",
                                      PreUniCountry_info_phd == "法国" ~ "French",
                                      PreUniCountry_info_phd == "香港" ~ "English",
                                      PreUniCountry_info_phd == "UK" ~ "English",
                                      PreUniCountry_info_phd == "日本东京" ~ "Japanese",
                                      PreUniCountry_info_phd == "英国剑桥" ~ "English")) %>%

  # Add new column for a continuous score for highest education, included all potential provided responses (to show coding scheme) and only the specific instances of other provided by participants
   mutate (HighestEdScore = dplyr::case_when (
                                             HighestEducation == "" ~ 0,
                                             HighestEducation == "NA" ~ 0,
                                             HighestEducation == "小学" ~ 4,
                                             HighestEducation == "中学" ~ 8,
                                             HighestEducation == "一些高中/中专、职高" ~ 10,
                                             HighestEducation == "高中" ~ 12,
                                             HighestEducation == "一些大专/高职/高专课程" ~ 14,
                                             HighestEducation == "部分本科课程" ~ 14,
                                             HighestEducation == "大专/高职/高专学位" ~ 15,
                                             HighestEducation == "本科" ~ 16,
                                             HighestEducation == "部分硕士课程" ~ 18,
                                             HighestEducation == "硕士" ~ 20,
                                             HighestEducation == "部分博士课程" ~ 22,
                                             HighestEducation == "博士" ~ 24
                                             )) %>% 
# Add new column for a continuous score for current education level (this will only be answered by those who say they are currently students)
  mutate (CurrentEdScore = dplyr::case_when (
                                             CurrentEd == "" ~ 0,
                                             CurrentEd == "NA" ~ 0,
                                             CurrentEd == "小学" ~ 4,
                                             CurrentEd == "中学" ~ 8,
                                             CurrentEd == "一些高中/中专、职高" ~ 10,
                                             CurrentEd == "高中" ~ 12,
                                             CurrentEd == "一些大专/高职/高专课程" ~ 14,
                                             CurrentEd == "部分本科课程" ~ 14,
                                             CurrentEd == "大专/高职/高专" ~ 15,
                                             CurrentEd == "本科" ~ 16,
                                             CurrentEd == "部分硕士课程" ~ 18,
                                             CurrentEd == "硕士" ~ 20,
                                             CurrentEd == "部分博士课程" ~ 22,
                                             CurrentEd == "博士" ~ 24
                                             )) %>% 
   unite (EducationScore, HighestEdScore, CurrentEdScore, HighestEd_Info, CurrentEd_Info,  remove = FALSE, na.rm = TRUE) %>% 
# When checking the data, there were either data for Highest Education or Current Education (based on the structure of the survey), this new variable combines the continuous scores into one variable that could be used when checking whether education level impacted the results.
  mutate  (HighestBiologyScore = dplyr::case_when (
                                                   HighestBiology == "无" ~ 0, 
                                                   HighestBiology == "取得初中毕业证书" ~ 8,
                                                   HighestBiology == "部分高中课程" ~ 10,
                                                   HighestBiology == "取得高中毕业证书" ~ 12,
                                                   HighestBiology == "部分本科课程" ~ 14,
                                                   HighestBiology == "取得本科学士学位" ~ 16,
                                                   HighestBiology == "部分硕士课程" ~ 18,
                                                   HighestBiology == "取得硕士学位" ~ 20,
                                                   HighestBiology == "部分博士课程" ~ 22,
                                                   HighestBiology == "取得博士学位" ~ 24,
                                                   HighestBiology == "" ~ 0,
                                                   HighestBiology == "NA" ~ 0)) %>% 
  mutate  (HighestChemistryScore = dplyr::case_when (HighestChemistry == "无" ~ 0, 
                                                     HighestChemistry == "取得初中毕业证书" ~ 8,
                                                     HighestChemistry == "部分高中课程" ~ 10,
                                                     HighestChemistry == "取得高中毕业证书" ~ 12,
                                                     HighestChemistry == "部分本科课程" ~ 14,
                                                     HighestChemistry == "取得本科学士学位" ~ 16,
                                                     HighestChemistry == "部分硕士课程" ~ 18,
                                                     HighestChemistry == "取得硕士学位" ~ 20,
                                                     HighestChemistry == "部分博士课程" ~ 22,
                                                     HighestChemistry == "取得博士学位" ~ 24,
                                                     HighestChemistry == "" ~ 0,
                                                     HighestChemistry == "NA" ~ 0
                                                     )) %>% 
  mutate  (HighestPhysicsScore = dplyr::case_when (HighestPhysics == "无" ~ 0, 
                                                   HighestPhysics == "取得初中毕业证书" ~ 8,
                                                   HighestPhysics == "部分高中课程" ~ 10,
                                                   HighestPhysics == "取得高中毕业证书" ~ 12,
                                                   HighestPhysics == "部分本科课程" ~ 14,
                                                   HighestPhysics == "取得本科学士学位" ~ 16,
                                                   HighestPhysics == "部分硕士课程" ~ 18,
                                                   HighestPhysics == "取得硕士学位" ~ 20,
                                                   HighestPhysics == "部分博士课程" ~ 22,
                                                   HighestPhysics == "取得博士学位" ~ 24,
                                                   HighestPhysics == "" ~ 0,
                                                   HighestPhysics == "NA" ~ 0)) %>% 
  mutate  (HighestEngineeringScore = dplyr::case_when (HighestEngineering == "无" ~ 0, 
                                                       HighestEngineering == "取得初中毕业证书" ~ 8,
                                                       HighestEngineering == "部分高中课程" ~ 10,
                                                       HighestEngineering == "取得高中毕业证书" ~ 12,
                                                       HighestEngineering == "部分本科课程" ~ 14,
                                                       HighestEngineering == "取得本科学士学位" ~ 16,
                                                       HighestEngineering == "部分硕士课程" ~ 18,
                                                       HighestEngineering == "取得硕士学位" ~ 20,
                                                       HighestEngineering == "部分博士课程" ~ 22,
                                                       HighestEngineering == "取得博士学位" ~ 24,
                                                       HighestEngineering == "" ~ 0,
                                                       HighestEngineering == "NA" ~ 0)) %>% 
  mutate  (HighestMathematicsScore = dplyr::case_when (HighestMathematics == "无" ~ 0, 
                                                       HighestMathematics == "取得初中毕业证书" ~ 8,
                                                       HighestMathematics == "部分高中课程" ~ 10,
                                                       HighestMathematics == "取得高中毕业证书" ~ 12,
                                                       HighestMathematics == "部分本科课程" ~ 14,
                                                       HighestMathematics == "取得本科学士学位" ~ 16,
                                                       HighestMathematics == "部分硕士课程" ~ 18,
                                                       HighestMathematics == "取得硕士学位" ~ 20,
                                                       HighestMathematics == "部分博士课程" ~ 22,
                                                       HighestMathematics == "取得博士学位" ~ 24,
                                                       HighestMathematics == "" ~ 0,
                                                       HighestMathematics == "NA" ~ 0)) %>% 
  mutate  (HighestPsychologyScore = dplyr::case_when (HighestPsychology == "无" ~ 0, 
                                                      HighestPsychology == "取得初中毕业证书" ~ 8,
                                                      HighestPsychology == "部分高中课程" ~ 10,
                                                      HighestPsychology == "取得高中毕业证书" ~ 12,
                                                      HighestPsychology == "部分本科课程" ~ 14,
                                                      HighestPsychology == "取得本科学士学位" ~ 16,
                                                      HighestPsychology == "部分硕士课程" ~ 18,
                                                      HighestPsychology == "取得硕士学位" ~ 20,
                                                      HighestPsychology == "部分博士课程" ~ 22,
                                                      HighestPsychology == "取得博士学位" ~ 24,
                                                      HighestPsychology == "" ~ 0,
                                                      HighestPsychology == "NA" ~ 0)) %>% 
  mutate  (HighestOtherScienceScore = dplyr::case_when (HighestOtherScience == "无" ~ 0, 
                                                         HighestOtherScience == "取得初中毕业证书" ~ 8,
                                                         HighestOtherScience == "部分高中课程" ~ 10,
                                                         HighestOtherScience == "取得高中毕业证书" ~ 12,
                                                         HighestOtherScience == "部分本科课程" ~ 14,
                                                         HighestOtherScience == "取得本科学士学位" ~ 16,
                                                         HighestOtherScience == "部分硕士课程" ~ 18,
                                                         HighestOtherScience == "取得硕士学位" ~ 20,
                                                         HighestOtherScience == "部分博士课程" ~ 22,
                                                         HighestOtherScience == "取得博士学位" ~ 24,
                                                         HighestOtherScience == "" ~ 0,
                                                         HighestOtherScience == "NA" ~ 0))
```

```{r Save file}
DEMOdata <- dplyr::select(.data = DEMOprocess, ParticipantID, Age, Gender, CN_FirstLanguage, Site, EducationScore, CurrentEdScore, HighestEdScore, HighestBiologyScore, HighestChemistryScore, HighestPhysicsScore, HighestEngineeringScore, HighestMathematicsScore, HighestPsychologyScore, HighestOtherScienceScore) %>% 

mutate (STEMscore = HighestBiologyScore + HighestPhysicsScore) #Since our explanatory coexistence task includes both biological and physical knowledge, we create a STEM score here, which will be used later in the analysis as a variable representing the level of biological and physical education.
write.csv(DEMOdata, "Qualtrics_CN.csv",row.names = FALSE) # Save as a CSV file that can be combined with the PsychoPy CSV files later
```

